- name: "Install and run nginx"
  hosts: local
  become: true
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 02.nginx.yaml      
